name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
         sudo apt-get update
         sudo apt-get install npm
         sudo npm i -g formality-js
         git clone --depth=1 https://github.com/moonad/formality formality
#         rm -rf formality/.git
      - name: Typecheck
        working-directory: formality/src
        run: |
          find . -name '*.fm' -exec fmjs {} \;
#          fmjs Main.fm
