name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
         sudo apt-get update
         sudo apt-get install npm
         sudo npm i -g formality-js
         git clone --depth=1 https://github.com/moonad/formality .
         rm -rf .git
         ls
      - uses: actions/checkout@v2
      - name: Typecheck
        run:  cd /src
      - run: fmjs Main.fm
